export interface Entity {
  slug: string;
  name: string;
  type: 'state' | 'territory' | 'dc';
  url: string;
}

export const ENTITIES: Entity[] = [
  { slug: 'alabama', name: 'Alabama', type: 'state', url: 'https://www.alabama.gov' },
  { slug: 'alaska', name: 'Alaska', type: 'state', url: 'https://www.alaska.gov' },
  { slug: 'arizona', name: 'Arizona', type: 'state', url: 'https://www.arizona.gov' },
  { slug: 'arkansas', name: 'Arkansas', type: 'state', url: 'https://www.arkansas.gov' },
  { slug: 'california', name: 'California', type: 'state', url: 'https://www.ca.gov' },
  { slug: 'colorado', name: 'Colorado', type: 'state', url: 'https://www.colorado.gov' },
  { slug: 'connecticut', name: 'Connecticut', type: 'state', url: 'https://www.ct.gov' },
  { slug: 'delaware', name: 'Delaware', type: 'state', url: 'https://www.delaware.gov' },
  { slug: 'florida', name: 'Florida', type: 'state', url: 'https://www.florida.gov' },
  { slug: 'georgia', name: 'Georgia', type: 'state', url: 'https://georgia.gov' },
  { slug: 'hawaii', name: 'Hawaii', type: 'state', url: 'https://www.hawaii.gov' },
  { slug: 'idaho', name: 'Idaho', type: 'state', url: 'https://www.idaho.gov' },
  { slug: 'illinois', name: 'Illinois', type: 'state', url: 'https://www.illinois.gov' },
  { slug: 'indiana', name: 'Indiana', type: 'state', url: 'https://www.in.gov' },
  { slug: 'iowa', name: 'Iowa', type: 'state', url: 'https://www.iowa.gov' },
  { slug: 'kansas', name: 'Kansas', type: 'state', url: 'https://www.kansas.gov' },
  { slug: 'kentucky', name: 'Kentucky', type: 'state', url: 'https://www.kentucky.gov' },
  { slug: 'louisiana', name: 'Louisiana', type: 'state', url: 'https://www.louisiana.gov' },
  { slug: 'maine', name: 'Maine', type: 'state', url: 'https://www.maine.gov' },
  { slug: 'maryland', name: 'Maryland', type: 'state', url: 'https://www.maryland.gov' },
  { slug: 'massachusetts', name: 'Massachusetts', type: 'state', url: 'https://www.mass.gov' },
  { slug: 'michigan', name: 'Michigan', type: 'state', url: 'https://www.michigan.gov' },
  { slug: 'minnesota', name: 'Minnesota', type: 'state', url: 'https://www.mn.gov' },
  { slug: 'mississippi', name: 'Mississippi', type: 'state', url: 'https://www.ms.gov' },
  { slug: 'missouri', name: 'Missouri', type: 'state', url: 'https://www.mo.gov' },
  { slug: 'montana', name: 'Montana', type: 'state', url: 'https://www.mt.gov' },
  { slug: 'nebraska', name: 'Nebraska', type: 'state', url: 'https://www.nebraska.gov' },
  { slug: 'nevada', name: 'Nevada', type: 'state', url: 'https://www.nv.gov' },
  { slug: 'new-hampshire', name: 'New Hampshire', type: 'state', url: 'https://www.nh.gov' },
  { slug: 'new-jersey', name: 'New Jersey', type: 'state', url: 'https://www.nj.gov' },
  { slug: 'new-mexico', name: 'New Mexico', type: 'state', url: 'https://www.newmexico.gov' },
  { slug: 'new-york', name: 'New York', type: 'state', url: 'https://www.ny.gov' },
  { slug: 'north-carolina', name: 'North Carolina', type: 'state', url: 'https://www.nc.gov' },
  { slug: 'north-dakota', name: 'North Dakota', type: 'state', url: 'https://www.nd.gov' },
  { slug: 'ohio', name: 'Ohio', type: 'state', url: 'https://www.ohio.gov' },
  { slug: 'oklahoma', name: 'Oklahoma', type: 'state', url: 'https://www.oklahoma.gov' },
  { slug: 'oregon', name: 'Oregon', type: 'state', url: 'https://www.oregon.gov' },
  { slug: 'pennsylvania', name: 'Pennsylvania', type: 'state', url: 'https://www.pa.gov' },
  { slug: 'rhode-island', name: 'Rhode Island', type: 'state', url: 'https://www.ri.gov' },
  { slug: 'south-carolina', name: 'South Carolina', type: 'state', url: 'https://www.sc.gov' },
  { slug: 'south-dakota', name: 'South Dakota', type: 'state', url: 'https://www.sd.gov' },
  { slug: 'tennessee', name: 'Tennessee', type: 'state', url: 'https://www.tn.gov' },
  { slug: 'texas', name: 'Texas', type: 'state', url: 'https://www.texas.gov' },
  { slug: 'utah', name: 'Utah', type: 'state', url: 'https://www.utah.gov' },
  { slug: 'vermont', name: 'Vermont', type: 'state', url: 'https://www.vermont.gov' },
  { slug: 'virginia', name: 'Virginia', type: 'state', url: 'https://www.virginia.gov' },
  { slug: 'washington', name: 'Washington', type: 'state', url: 'https://www.wa.gov' },
  { slug: 'west-virginia', name: 'West Virginia', type: 'state', url: 'https://www.wv.gov' },
  { slug: 'wisconsin', name: 'Wisconsin', type: 'state', url: 'https://www.wisconsin.gov' },
  { slug: 'wyoming', name: 'Wyoming', type: 'state', url: 'https://www.wyoming.gov' },
  // DC
  { slug: 'dc', name: 'Washington D.C.', type: 'dc', url: 'https://dc.gov' },
  // Territories
  { slug: 'puerto-rico', name: 'Puerto Rico', type: 'territory', url: 'https://www.pr.gov' },
  { slug: 'guam', name: 'Guam', type: 'territory', url: 'https://www.guam.gov' },
  { slug: 'us-virgin-islands', name: 'US Virgin Islands', type: 'territory', url: 'https://www.vi.gov' },
  { slug: 'american-samoa', name: 'American Samoa', type: 'territory', url: 'https://www.americansamoa.gov' },
  { slug: 'northern-mariana-islands', name: 'N. Mariana Islands', type: 'territory', url: 'https://www.cnmi.gov' },
];
